language: node_js
node_js:
  - "8"
before_deploy: npm run build
deploy:
  provider: npm
  email: rubixibuc@gmail.com
  api_key:
    secure: QDAPPNIBk/QYyMJ31LqST5gBMU5Ed1euZKCTU3kullorBYiOSQjO0F8sSc6qbuBlOefU3RoT/uTNSWyzmozymZA5d4+l9Lp5JD8HeNzWkZ80OcePZR3pJ10C2t2PayU4wuPLcEVVfg80qbzfvzMBIoL8YgeTVTrMhQMGIczi7dkYlTVZpCwAx+xn9igkfAqaXD1WkMz6fY4KO1+3DCvcdRKB5FQDCVMTQoj3AvtoPQYDHIfrG3UWs0Vh9A07B3UBq4LjCzwjzUQHr8myBGTYH08x0n4/lPKSFt07hhPlGgyJ3+eY5lT7cPLW1jmpmrV0/E8UfpooBgTgJ9ZUC84kleX76x0NVG+/5EDuaPgMDc9Un7mlCz36QxV1IVqKipqt0a+PoR+tijDl/4opmkjyslUUM8djYoSFPgFwZUwMAM9lMnotCgxRumezIpUW837YmweBLF1VaIW1YhyRfawrxZZVqBSc3Xk8NnH6urEn2vw8HNoIe81ysF/8G2CqBSO+poAvYoNFlv89OyVnDSETRu+dUFWG/4E5zAUnVlNo5H2xQ59q96aQZkPHmdU43yVYtRFzSlRztyPUUzfcberqTgnZo+IANiNpIUuOlgPEHuInny4SS+ytlwSlQfLbNk+GlosIXk7V/nZ1G5OW01Fhq8QDZxWi8+RfxMWaFOzIVbU=
  on:
    tags: true
    repo: rubixibuc/with-styles
  skip_cleanup: true
